/**
 * \file cpu0_main.h
 * \brief CPU0主程序头文件 - 系统初始化和应用程序信息定义
 *
 * \version iLLD_Demos_1_0_1_11_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * \defgroup IfxLld_Demo_STMDemo_SrcDoc Source code documentation
 * \ingroup IfxLld_Demo_STMDemo
 */

#ifndef CPU0_MAIN_H
#define CPU0_MAIN_H

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include "Cpu/Std/Ifx_Types.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Type Definitions------------------------------*/
/******************************************************************************/

/**
 * @brief 应用信息结构体 - 存储系统时钟频率信息
 *
 * 记录TC264D各模块的实际工作频率，用于：
 *   - 验证时钟配置是否正确
 *   - 计算定时器周期、波特率等参数
 *   - 调试时查看系统运行状态
 */
typedef struct
{
    float32 sysFreq;    /**< SPB（系统外设总线）实际频率（Hz），外设时钟基准 */
    float32 cpuFreq;    /**< CPU实际频率（Hz），决定指令执行速度 */
    float32 pllFreq;    /**< PLL（锁相环）实际频率（Hz），系统主时钟源 */
    float32 stmFreq;    /**< STM（系统定时器）实际频率（Hz），用于精确计时 */
} AppInfo;

/**
 * @brief CPU0应用结构体 - 包含CPU0的应用信息
 *
 * 在系统启动时由 clock_init() 填充各频率字段。
 * 可通过 g_AppCpu0.info 访问系统时钟信息。
 */
typedef struct
{
    AppInfo info;       /**< 系统时钟频率信息 */
} App_Cpu0;

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

IFX_EXTERN App_Cpu0 g_AppCpu0;  /**< CPU0应用信息全局实例，存储系统时钟频率 */

#endif
